### ISSUE TITLE
Install/setup not working in Portainer

### ISSUE THREAD

**Issue by jordanhinks** [psychowood/hyperion.ng-docker#2]
While attempting to install this via the Standard or Standalone config in Portainer neither properly install.

From checking the logs, the same info entry keeps appearing stating "addgroup: The group `hyperion' already exists."

**Comment by psychowood** [comment]
Can you provide the full container log?

AFAIK Portainer does not support binding local directories as volumes, did you edit the compose file?

**Comment by jordanhinks** [comment]
I didn't edit the compose file, I did try performing the Standard configuration outside of Portainer just in the command line itself but experienced a different issue regarding it not being able to build the docker container as states the folder doesn't exist but it did.

Please see attached log file for when I run the standalone configuration.

[_hyperion_logs.txt](https://github.com/psychowood/hyperion.ng-docker/files/9229641/_hyperion_logs.txt)

**Comment by jordanhinks** [comment]
If it's of any help, I also just ran the docker-compose standalone as per the instructions directly on the Pi without Portainer and I believe it experiences the same issue, log attached.

[hyperion log manual standalone.txt](https://github.com/psychowood/hyperion.ng-docker/files/9246189/hyperion.log.manual.standalone.txt)
 
I did also try the basic setup again not in Portainer and it doesn't seem to work either.

**Comment by BenBattler** [comment]
I'm having the same issue, i tried building the image from a dockerfile, docker-composing the container from a yml as well as just using a docker run command. I also tried using a debain:buster base instead of bullseye but it didn't change anything (maybe it shouldn't, I don't know..). I also ran just the first line of the bash command (addgroup) and this is where the error occurs. Log is the same as @jordanhinks '.

I would really love to run Hyperion-NG in a container but so far I seem to have tried everything. You have the most indepth manual of all but I still can't get it to work.. The great is thing this way I'm learning docker so for what it's worth: thank you very much for actually letting me try to figure stuff out and not just providing a buttoned-up solution, even if it might should have been that way ;)

**Comment by psychowood** [comment]
Sorry if I haven't been able to reply, I'm not really using this script anymore since I'm running hyperion.ng directly on my LG tv.
I'll try to replicate the issue the next weekend, in the meanwhile you can give a look at this repo https://github.com/foorschtbar/hyperion-docker

**Comment by BenBattler** [comment]
Hey thanks for your quick answer. I tried this one already as well but I'm going to retry. I see! I guess running it right on the tv might be more straightforward for setting it up. In my use case it's a Windows PC which displays the content.

**Comment by psychowood** [comment]
I've just pushed some changes, everything is running fine on my end, I've tested both the standard and the standalone version. As a bonus I added a nightly build file too :)

Notable changes:
- moved away from bullseye-slim to bullseye (fixed a missing .so library error)
- moved configuration to a standard docker volume instead of a binded directory to prevent ownership errors
- add some controls to prevent fails if the internal user was already created

**Comment by BenBattler** [comment]
Awesome, thanks! I will check it out as soon as possible!

**Comment by BenBattler** [comment]
I tried it on a fresh Pi with Bullseye on it, the error due to the group already existing is mitigated now, an error concerning a missing library (libatomic.so.1) still appeared. I just added a line in the bash script to install it as well and not it works for me. Huge thanks!
